version: "2"

networks:
  nexus:
    external: false

services:
  server:
    image: sonatype/nexus3:3.19.1
    restart: always
    networks:
      - nexus
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8123:8123"
