version: "2"

networks:
  cicd:
    external: false

services:
  gitea-server:
    image: gitea/gitea:1.10.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea    
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
      - APP_NAME="GITEA TEST SERVER"  
    restart: always
    networks:
      - cicd
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:3000"
      - "2222:22"
    depends_on:
      - gitea-db

  gitea-db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - cicd
    volumes:
      - ./postgres-data:/var/lib/postgresql/data      

  nexus-server:
    image: sonatype/nexus3:3.19.1
    restart: always
    networks:
      - cicd
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8123:8123"

  concourse-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    networks:
      - cicd      
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  concourse-web:
    image: concourse/concourse:5.7.2
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    networks:
      - cicd    
    environment:
      CONCOURSE_EXTERNAL_URL: http://cicd:8080
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: admin:admin123!@#
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  concourse-worker:
    image: concourse/concourse:5.7.2
    command: worker
    privileged: true
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [concourse-web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
    networks:
      - cicd      
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"